---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
  namespace: openshift-policy
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: placement-hub-openshift
              requeueAfterSeconds: 180
          - git:
              repoURL: https://github.com/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/etx-agentic-ai.git
              revision: main
              directories:
                - path: infra/tenants/*/base/sno
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: tenant-{{index (splitList "/" .path.path) 2}}-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: tenants
      source:
        repoURL: https://github.com/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/etx-agentic-ai.git
        path: "{{.path.path}}"
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
